version: '3.0'
services:
  nginx_cont:
  image: nginx
  ports:
    - "80:80"
  volumes:
     - /home/ec2-user/dir:/abc

  jenkins_cont:
    image: jenkins/jenkins
    ports:
      - "12.8080"
    volumes:
      - /home/ec2-user/gen:/bin

  mysql_cont:
    images: mysql
    ports:
      - "3306:3306"

    volumes:
      - /home/ec2-user/sql:/bin
    environment:
      - MQSQL_ROOT_PASSWORD:secretpass
    

